### ISSUE TITLE
Request processed datasets

### ISSUE THREAD

**Issue by yimutianyang** [nickwzk/InvRL#1]
Hi~ I'm interested in this work! Can you provide all processed datasets for reproduction? Looking forward to your reply.

**Comment by nickwzk** [comment]
Hi @yimutianyang,
thanks for your attention. Please download it from the following URL: https://drive.google.com/drive/folders/1nwUM_NyvcQWlkrXfFRVwkVHwVqkVRsmS?usp=sharing

**Comment by yimutianyang** [comment]
Thanks a lot~
